# PYTHON

https:/￼/python2022.netlify.app/

https://docs.python.org/3/library/index.html Documentación Python

https://pandas.pydata.org/docs/user_guide/index.html Documentación Pandas

In [1]:
import os #Manejo del sistema operativo
import pandas as pd #Análisis y manipulación de datos.
import numpy as np #computación científica y manipulación eficiente de arreglos multidimensionales.

#Configura el formato para que los números se muestren con dos decimales y se separen por comas para facilitar la lectura.
pd.options.display.float_format = '{:,.2f}'.format

### Personalizando el directorio de trabajo

In [2]:
#Work directory
os.chdir("/root/work/AiRoute/university-stuff/statistical_computing/Python")
os.getcwd()

#Ruta data sets
datasets = "/datasets/university-drive/Curso/"

### Ejemplos:

In [3]:
#1 - Primera fila contiene los nombres de las variables.
plantulas1 = pd.read_excel(datasets + "sample.xlsx",sheet_name=12,header=0)
plantulas1.info()
plantulas1.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Parcela   55 non-null     int64
 1   NI        55 non-null     int64
 2   Plantula  55 non-null     int64
 3   Ni        55 non-null     int64
 4   Altura    55 non-null     int64
dtypes: int64(5)
memory usage: 2.3 KB

   Parcela  NI  Plantula  Ni  Altura
0        3  50         1  52      12
1        3  50         2  52      11
2        3  50         3  52      12
3        3  50         4  52      10
4        3  50         5  52      13
5        6  50         6  56      10
6        6  50         7  56       9
7        6  50         8  56       7
8        6  50         9  56       9
9        6  50        10  56       8

In [4]:
#2
plantulas2 = pd.read_excel(datasets + "sample.xlsx",sheet_name="Plantulas",header=0)
plantulas2.info()
plantulas2.tail(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Parcela   55 non-null     int64
 1   NI        55 non-null     int64
 2   Plantula  55 non-null     int64
 3   Ni        55 non-null     int64
 4   Altura    55 non-null     int64
dtypes: int64(5)
memory usage: 2.3 KB

    Parcela  NI  Plantula  Ni  Altura
45       33  50        46  60       8
46       33  50        47  60       9
47       33  50        48  60       9
48       33  50        49  60      10
49       50  50        50  45      12
50       50  50        51  45      11
51       50  50        52  45      12
52       50  50        53  45      13
53       50  50        54  45      12
54       50  50        55  45      12

In [5]:
#3 - Columnas "A", "B", "C" y "E"
plantulas3 = pd.read_excel(datasets + "sample.xlsx",sheet_name="Plantulas",usecols="A:C,E",header=0)
plantulas3.info()
plantulas3.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Parcela   55 non-null     int64
 1   NI        55 non-null     int64
 2   Plantula  55 non-null     int64
 3   Altura    55 non-null     int64
dtypes: int64(4)
memory usage: 1.8 KB

   Parcela  NI  Plantula  Altura
0        3  50         1      12
1        3  50         2      11
2        3  50         3      12
3        3  50         4      10
4        3  50         5      13
5        6  50         6      10
6        6  50         7       9
7        6  50         8       7
8        6  50         9       9
9        6  50        10       8

In [6]:
#4 - Primera 35 filas
plantulas4 = pd.read_excel(datasets + "sample.xlsx",sheet_name="Plantulas",nrows=35,header=0)
plantulas4.info()
plantulas4.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Parcela   35 non-null     int64
 1   NI        35 non-null     int64
 2   Plantula  35 non-null     int64
 3   Ni        35 non-null     int64
 4   Altura    35 non-null     int64
dtypes: int64(5)
memory usage: 1.5 KB

   Parcela  NI  Plantula  Ni  Altura
0        3  50         1  52      12
1        3  50         2  52      11
2        3  50         3  52      12
3        3  50         4  52      10
4        3  50         5  52      13
5        6  50         6  56      10
6        6  50         7  56       9
7        6  50         8  56       7
8        6  50         9  56       9
9        6  50        10  56       8

In [7]:
#5 - Nombres personalizados a las variables
plantulas5 = pd.read_excel(datasets + "sample.xlsx",sheet_name="Plantulas",header=0,
                           names=["IdParcela","N_I","IdPlantula","N_i","Altura"])
plantulas5.info()
plantulas5.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   IdParcela   55 non-null     int64
 1   N_I         55 non-null     int64
 2   IdPlantula  55 non-null     int64
 3   N_i         55 non-null     int64
 4   Altura      55 non-null     int64
dtypes: int64(5)
memory usage: 2.3 KB

   IdParcela  N_I  IdPlantula  N_i  Altura
0          3   50           1   52      12
1          3   50           2   52      11
2          3   50           3   52      12
3          3   50           4   52      10
4          3   50           5   52      13
5          6   50           6   56      10
6          6   50           7   56       9
7          6   50           8   56       7
8          6   50           9   56       9
9          6   50          10   56       8

In [8]:
#6 - Formato text, numeric, text, numeric y numeric, respectivamente.
plantulas6 = pd.read_excel(datasets + "sample.xlsx",sheet_name="Plantulas",header=0,
                          names=["IdParcela","N_I","IdPlantula","N_i","Altura"],
                          dtype={"IdParcela":str,"N_I":np.int64,"IdPlantula":str,
                                 "N_i":np.float64,"Altura":np.float64})
plantulas6.info()
plantulas6.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   IdParcela   55 non-null     object
 1   N_I         55 non-null     int64
 2   IdPlantula  55 non-null     object
 3   N_i         55 non-null     float64
 4   Altura      55 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 2.3+ KB

  IdParcela  N_I IdPlantula   N_i  Altura
0         3   50          1 52.00   12.00
1         3   50          2 52.00   11.00
2         3   50          3 52.00   12.00
3         3   50          4 52.00   10.00
4         3   50          5 52.00   13.00
5         6   50          6 56.00   10.00
6         6   50          7 56.00    9.00
7         6   50          8 56.00    7.00
8         6   50          9 56.00    9.00
9         6   50         10 56.00    8.00

In [9]:
#7 - La segunda variable se excluye y el tipo de la cuarta variable se especifica a partir de una inspección de los datos.
plantulas7 = pd.read_excel(datasets + "sample.xlsx",sheet_name="Plantulas",header=0,usecols=[0,2,3,4],
                           names=["IdParcela","IdPlantula","N_i","Altura"],
                           dtype={"IdParcela":str,"IdPlantula":str,"Altura":np.float64})
plantulas7.info()
plantulas7.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   IdParcela   55 non-null     object
 1   IdPlantula  55 non-null     object
 2   N_i         55 non-null     int64
 3   Altura      55 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.8+ KB

  IdParcela IdPlantula  N_i  Altura
0         3          1   52   12.00
1         3          2   52   11.00
2         3          3   52   12.00
3         3          4   52   10.00
4         3          5   52   13.00
5         6          6   56   10.00
6         6          7   56    9.00
7         6          8   56    7.00
8         6          9   56    9.00
9         6         10   56    8.00

In [10]:
#8 -  Los datos están separados por " "
stocks1 = pd.read_table(datasets + "stocks.dlm",delimiter=" ",header=0)
stocks1.info()
stocks1.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       699 non-null    object
 1   B       699 non-null    object
 2   C       699 non-null    object
 3   D       699 non-null    object
 4   E       699 non-null    object
 5   F       699 non-null    object
 6   G       699 non-null    object
 7   H       699 non-null    object
dtypes: object(8)
memory usage: 43.8+ KB

     A        B      C      D      E      F           G      H
0  IBM  01DEC05  89,15  89,92  81,56  82,20   5.976.252  81,37
1  IBM  01NOV05  81,85  89,94  80,64  88,90   5.556.471  88,01
2  IBM  03OCT05  80,22  84,60  78,70  81,88   7.019.666  80,86
3  IBM  01SEP05  80,16  82,11  76,93  80,22   5.772.280  79,22
4  IBM  01AUG05  83,00  84,20  79,87  80,62   4.801.386  79,62
5  IBM  01JUL05  74,30  85,11  74,16  83,46   8.056.590  82,23
6  IBM  01JUN05  75,57  77,73  73,45  74,20   6.439.536  73,10
7  IBM  02MAY05  76,88  78,11  72,50  75,55   6.896.904  74,43
8  IBM  01APR05  91,49  91,76  71,85  76,38  10.709.200  75,05
9  IBM  01MAR05  92,64  93,73  89,09  91,38   5.025.627  89,79

In [11]:
#9 -  Separador decimal es "," y el separador de agrupamiento es ".".
stocks2 = pd.read_table(datasets + "stocks.dlm",delimiter=" ",decimal=",",thousands=".",header=0)
stocks2.info()
stocks2.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       699 non-null    object
 1   B       699 non-null    object
 2   C       699 non-null    float64
 3   D       699 non-null    float64
 4   E       699 non-null    float64
 5   F       699 non-null    float64
 6   G       699 non-null    int64
 7   H       699 non-null    float64
dtypes: float64(5), int64(1), object(2)
memory usage: 43.8+ KB

     A        B     C     D     E     F         G     H
0  IBM  01DEC05 89.15 89.92 81.56 82.20   5976252 81.37
1  IBM  01NOV05 81.85 89.94 80.64 88.90   5556471 88.01
2  IBM  03OCT05 80.22 84.60 78.70 81.88   7019666 80.86
3  IBM  01SEP05 80.16 82.11 76.93 80.22   5772280 79.22
4  IBM  01AUG05 83.00 84.20 79.87 80.62   4801386 79.62
5  IBM  01JUL05 74.30 85.11 74.16 83.46   8056590 82.23
6  IBM  01JUN05 75.57 77.73 73.45 74.20   6439536 73.10
7  IBM  02MAY05 76.88 78.11 72.50 75.55   6896904 74.43
8  IBM  01APR05 91.49 91.76 71.85 76.38  10709200 75.05
9  IBM  01MAR05 92.64 93.73 89.09 91.38   5025627 89.79

In [13]:
#10 - Especificando el formato en el que se deben leer las variables.
from datetime import datetime
dateparse = lambda x: datetime.strptime(x,"%d%b%y")

stocks3 = pd.read_table(datasets + "stocks.dlm",delimiter=" ",decimal=",",thousands=".",header=0,
                        dtype={"A":str,"B":str,"C":np.float64,"D":np.float64,"E":np.float64,
                              "F":np.float64,"G":np.float64,"H":np.float64},
                        parse_dates=["B"], date_parser=dateparse)

stocks3.info()
stocks3.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       699 non-null    object
 1   B       699 non-null    datetime64[ns]
 2   C       699 non-null    float64
 3   D       699 non-null    float64
 4   E       699 non-null    float64
 5   F       699 non-null    float64
 6   G       699 non-null    float64
 7   H       699 non-null    float64
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 43.8+ KB

     A          B     C     D     E     F             G     H
0  IBM 2005-12-01 89.15 89.92 81.56 82.20  5,976,252.00 81.37
1  IBM 2005-11-01 81.85 89.94 80.64 88.90  5,556,471.00 88.01
2  IBM 2005-10-03 80.22 84.60 78.70 81.88  7,019,666.00 80.86
3  IBM 2005-09-01 80.16 82.11 76.93 80.22  5,772,280.00 79.22
4  IBM 2005-08-01 83.00 84.20 79.87 80.62  4,801,386.00 79.62
5  IBM 2005-07-01 74.30 85.11 74.16 83.46  8,056,590.00 82.23
6  IBM 2005-06-01 75.57 77.73 73.45 74.20  6,439,536.00 73.10
7  IBM 2005-05-02 76.88 78.11 72.50 75.55  6,896,904.00 74.43
8  IBM 2005-04-01 91.49 91.76 71.85 76.38 10,709,200.00 75.05
9  IBM 2005-03-01 92.64 93.73 89.09 91.38  5,025,627.00 89.79

Formato fechas y horas https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=cd2fca3f-dc64-4c71-8bd4-adda531fa911' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>