In [2]:
import pandas as pd
import numpy as np

In [53]:
df = pd.read_csv('sources/all_games.csv')
df_games = df.copy()
df_games.head(15) # head(n primeros registros)

,name,platform,release_date,summary,meta_score,user_review
0,The Legend of Zelda: Ocarina of Time,Nintendo 64,"November 23, 1998","As a young boy, Link is tricked by Ganondorf, ...",99,9.1
1,Tony Hawk's Pro Skater 2,PlayStation,"September 20, 2000",As most major publishers' development efforts ...,98,7.4
2,Grand Theft Auto IV,PlayStation 3,"April 29, 2008",[Metacritic's 2008 PS3 Game of the Year; Also ...,98,7.7
3,SoulCalibur,Dreamcast,"September 8, 1999","This is a tale of souls and swords, transcendi...",98,8.4
4,Grand Theft Auto IV,Xbox 360,"April 29, 2008",[Metacritic's 2008 Xbox 360 Game of the Year; ...,98,7.9
5,Super Mario Galaxy,Wii,"November 12, 2007",[Metacritic's 2007 Wii Game of the Year] The u...,97,9.1
6,Super Mario Galaxy 2,Wii,"May 23, 2010","Super Mario Galaxy 2, the sequel to the galaxy...",97,9.1
7,Red Dead Redemption 2,Xbox One,"October 26, 2018",Developed by the creators of Grand Theft Auto ...,97,8.0
8,Grand Theft Auto V,Xbox One,"November 18, 2014",Grand Theft Auto 5 melds storytelling and game...,97,7.9
9,Grand Theft Auto V,PlayStation 3,"September 17, 2013","Los Santos is a vast, sun-soaked metropolis fu...",97,8.3
10,Disco Elysium: The Final Cut,PC,"March 30, 2021",Disco Elysium - The Final Cut is the definitiv...,97,8.3
11,Grand Theft Auto V,Xbox 360,"September 17, 2013",Los Santos is a sprawling sun-soaked metropoli...,97,8.3
12,Tony Hawk's Pro Skater 2,Dreamcast,"November 6, 2000","Hawk's back - with new technology, new pros an...",97,6.2
13,The Legend of Zelda: Breath of the Wild,Switch,"March 3, 2017",Forget everything you know about The Legend of...,97,8.7
14,Tony Hawk's Pro Skater 3,PlayStation 2,"October 28, 2001",Challenge up to four friends in online competi...,97,7.5

In [5]:
df_games.info() # Data frame information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18800 entries, 0 to 18799
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          18800 non-null  object
 1   platform      18800 non-null  object
 2   release_date  18800 non-null  object
 3   summary       18686 non-null  object
 4   meta_score    18800 non-null  int64
 5   user_review   18800 non-null  object
dtypes: int64(1), object(5)
memory usage: 881.4+ KB

In [6]:
df_games.describe() #Statisc info of some column datas

         meta_score
count  18800.000000
mean      70.648883
std       12.225006
min       20.000000
25%       64.000000
50%       72.000000
75%       80.000000
max       99.000000

,name,platform,release_date,summary,meta_score,user_review
18795,Fast & Furious: Showdown,Xbox 360,"May 21, 2013",Fast & Furious: Showdown takes some of the fra...,22,1.3
18796,Drake of the 99 Dragons,Xbox,"November 3, 2003",Drake is out for revenge in a supernatural Hon...,22,1.7
18797,Afro Samurai 2: Revenge of Kuma Volume One,PlayStation 4,"September 22, 2015","Head out on a journey of redemption, driven by...",21,2.9
18798,Infestation: Survivor Stories (The War Z),PC,"October 15, 2012","(Formerly known as ""The War Z"") It has been 5 ...",20,1.7
18799,Leisure Suit Larry: Box Office Bust,PC,"March 31, 2009",The Leisure Suit Larry: Box Office Bust video ...,20,2.0

In [10]:
df_games.memory_usage(deep = True)

Index                128
name             1470009
platform         1224059
release_date     1355338
summary         14834208
meta_score        150400
user_review      1128000
dtype: int64

In [11]:
df_games['platform'].value_counts()

 PC                  4864
 PlayStation 4       2056
 Xbox 360            1644
 PlayStation 2       1414
 Switch              1399
 PlayStation 3       1256
 Xbox One            1179
 Xbox                 789
 DS                   720
 Wii                  655
 PSP                  512
 GameCube             448
 Game Boy Advance     438
 3DS                  396
 PlayStation Vita     257
 PlayStation          187
 Wii U                184
 Dreamcast            125
 PlayStation 5        124
 Xbox Series X         77
 Nintendo 64           71
 Stadia                 5
Name: platform, dtype: int64

In [12]:
df_games.iloc[0]

name                         The Legend of Zelda: Ocarina of Time
platform                                              Nintendo 64
release_date                                    November 23, 1998
summary         As a young boy, Link is tricked by Ganondorf, ...
meta_score                                                     99
user_review                                                   9.1
Name: 0, dtype: object

In [16]:
df_games = df_games.append(df_games.iloc[0])#append a duplicate

/tmp/ipykernel_9338/388353289.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_games = df_games.append(df_games.iloc[0])

In [17]:
df_games

,name,platform,release_date,summary,meta_score,user_review
0,The Legend of Zelda: Ocarina of Time,Nintendo 64,"November 23, 1998","As a young boy, Link is tricked by Ganondorf, ...",99,9.1
1,Tony Hawk's Pro Skater 2,PlayStation,"September 20, 2000",As most major publishers' development efforts ...,98,7.4
2,Grand Theft Auto IV,PlayStation 3,"April 29, 2008",[Metacritic's 2008 PS3 Game of the Year; Also ...,98,7.7
3,SoulCalibur,Dreamcast,"September 8, 1999","This is a tale of souls and swords, transcendi...",98,8.4
4,Grand Theft Auto IV,Xbox 360,"April 29, 2008",[Metacritic's 2008 Xbox 360 Game of the Year; ...,98,7.9
...,...,...,...,...,...,...
18796,Drake of the 99 Dragons,Xbox,"November 3, 2003",Drake is out for revenge in a supernatural Hon...,22,1.7
18797,Afro Samurai 2: Revenge of Kuma Volume One,PlayStation 4,"September 22, 2015","Head out on a journey of redemption, driven by...",21,2.9
18798,Infestation: Survivor Stories (The War Z),PC,"October 15, 2012","(Formerly known as ""The War Z"") It has been 5 ...",20,1.7
18799,Leisure Suit Larry: Box Office Bust,PC,"March 31, 2009",The Leisure Suit Larry: Box Office Bust video ...,20,2.0
0,The Legend of Zelda: Ocarina of Time,Nintendo 64,"November 23, 1998","As a young boy, Link is tricked by Ganondorf, ...",99,9.1

In [26]:
df_games.drop_duplicates(inplace = True) #REAL delete a duplicate

In [27]:
df_games.sort_values('meta_score', ascending = True) #SORT VALUES

,name,platform,release_date,summary,meta_score,user_review
18799,Leisure Suit Larry: Box Office Bust,PC,"March 31, 2009",The Leisure Suit Larry: Box Office Bust video ...,20,2.0
18798,Infestation: Survivor Stories (The War Z),PC,"October 15, 2012","(Formerly known as ""The War Z"") It has been 5 ...",20,1.7
18797,Afro Samurai 2: Revenge of Kuma Volume One,PlayStation 4,"September 22, 2015","Head out on a journey of redemption, driven by...",21,2.9
18796,Drake of the 99 Dragons,Xbox,"November 3, 2003",Drake is out for revenge in a supernatural Hon...,22,1.7
18795,Fast & Furious: Showdown,Xbox 360,"May 21, 2013",Fast & Furious: Showdown takes some of the fra...,22,1.3
...,...,...,...,...,...,...
4,Grand Theft Auto IV,Xbox 360,"April 29, 2008",[Metacritic's 2008 Xbox 360 Game of the Year; ...,98,7.9
3,SoulCalibur,Dreamcast,"September 8, 1999","This is a tale of souls and swords, transcendi...",98,8.4
2,Grand Theft Auto IV,PlayStation 3,"April 29, 2008",[Metacritic's 2008 PS3 Game of the Year; Also ...,98,7.7
1,Tony Hawk's Pro Skater 2,PlayStation,"September 20, 2000",As most major publishers' development efforts ...,98,7.4
0,The Legend of Zelda: Ocarina of Time,Nintendo 64,"November 23, 1998","As a young boy, Link is tricked by Ganondorf, ...",99,9.1

# TEST
TOP USER REVIEW

In [63]:
df = pd.read_csv('sources/all_games.csv')
df_games = df.copy()

In [72]:
df_games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18800 entries, 0 to 18799
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          18800 non-null  object
 1   platform      18800 non-null  object
 2   release_date  18800 non-null  object
 3   summary       18686 non-null  object
 4   meta_score    18800 non-null  int64
 5   user_review   17435 non-null  float32
dtypes: float32(1), int64(1), object(4)
memory usage: 807.9+ KB

In [64]:
df_games['user_review'][df_games['user_review'] == 'tbd'] = np.nan

/tmp/ipykernel_9338/2321442801.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_games['user_review'][df_games['user_review'] == 'tbd'] = np.nan

In [73]:
df_games.dropna(inplace = True)

In [67]:
df_games['user_review'] = df_games['user_review'].astype('float32')

In [75]:
top_games_by_users = df_games.sort_values('user_review', ascending = False) 
top_games_by_users.head(15)

,name,platform,release_date,summary,meta_score,user_review
3504,Z.H.P. Unlosing Ranger vs Darkdeath Evilman,PSP,"October 25, 2010","Known as ZettaiHero Keikakuin Japan, Z.H.P. is...",81,9.7
9550,After Burner Climax,Xbox 360,"April 21, 2010",[Xbox Live Arcade] The classic arcade game Aft...,72,9.7
2450,Ghost Trick: Phantom Detective,DS,"January 11, 2011",Ghost Trick is a story of mystery and intrigue...,83,9.7
4844,GrimGrimoire,PlayStation 2,"June 26, 2007",Lillet Blan was very excited. Her heart had be...,79,9.7
14836,Metal Torrent,DS,"May 24, 2010",[DSiWare] Prepare for a high level of intensit...,62,9.7
4953,Rochard,PlayStation 3,"September 27, 2011",Players embrace the gravity-bending exploits o...,79,9.7
10936,Tengami,Wii U,"November 13, 2014","Set in Japan of ancient dark fairy tales, Teng...",70,9.7
12434,Crystar,PlayStation 4,"August 27, 2019","For when I weep, then I am strong. Battle thro...",67,9.6
7638,Superliminal,Switch,"July 7, 2020",Perception is reality. Escape from a mind-bend...,75,9.6
4573,Superliminal,Xbox One,"July 7, 2020",Perception is reality. In this mind-bending fi...,80,9.6
11304,Diaries of a Spaceport Janitor,PC,"September 16, 2016",Diaries of a Spaceport Janitor is an anti-adve...,69,9.6
114,The Witcher 3: Wild Hunt,PC,"May 18, 2015",With the Empire attacking the Kingdoms of the ...,93,9.4
267,The Witcher 3: Wild Hunt - Blood and Wine,PC,"May 30, 2016",This expansion pack is an old-school add on wi...,92,9.3
32,The Orange Box,PC,"October 10, 2007",Games included in The Orange Box compilation: ...,96,9.3
2407,Astro's Playroom,PlayStation 5,"November 12, 2020",Astro and his crew lead you on a magical intro...,83,9.3

In [76]:
top_games_by_users['user_review'].skew() #El rating segun los usuarios tiende a sér negativo

-1.2133429

In [77]:
top_games_by_users['meta_score'].skew() #El rating segun los medios tiende a sér un poco menos negativo

-0.8320048767563314