Documentation: https://r2022.netlify.app/

In [1]:
install.packages("readxl")
library(readxl)

Installing package into ‘/work/.R/library’
(as ‘lib’ is unspecified)

## View DataFrame

### Base

read_excel(
  path,
  sheet = NULL,
  range = NULL,
  col_names = TRUE,
  col_types = NULL,
  na = "",
  trim_ws = TRUE,
  skip = 0,
  n_max = Inf,
  guess_max = min(1000, n_max),
  progress = readxl_progress(),
  .name_repair = "unique"
)

In [12]:
p1 <- read_excel("sample (1).xlsx", sheet=13, col_names=TRUE)
p1

   Parcela NI Plantula Ni Altura
1   3      50  1       52 12
2   3      50  2       52 11
3   3      50  3       52 12
4   3      50  4       52 10
5   3      50  5       52 13
6   6      50  6       56 10
7   6      50  7       56  9
8   6      50  8       56  7
9   6      50  9       56  9
10  6      50 10       56  8
11  6      50 11       56 10
12  8      50 12       60  6
13  8      50 13       60  5
14  8      50 14       60  7
15  8      50 15       60  5
16  8      50 16       60  6
17  8      50 17       60  4
18 15      50 18       46  7
19 15      50 19       46  8
20 15      50 20       46  7
21 15      50 21       46  7
22 15      50 22       46  6
23 22      50 23       49 10
24 22      50 24       49 11
25 22      50 25       49 13
26 22      50 26       49 12
27 22      50 27       49 12
28 24      50 28       51 14
29 24      50 29       51 15
30 24      50 30       51 13
31 24      50 31       51 12
32 24      50 32       51 13
33 30      50 33       50  6
34 30      50 34       50  7
35 30      50 35       50  6
36 30      50 36       50  8
37 30      50 37       50  7
38 32      50 38       61  9
39 32      50 39       61 10
40 32      50 40       61  8
41 32      50 41       61  9
42 32      50 42       61  9
43 32      50 43       61 10
44 33      50 44       60  7
45 33      50 45       60 10
46 33      50 46       60  8
47 33      50 47       60  9
48 33      50 48       60  9
49 33      50 49       60 10
50 50      50 50       45 12
51 50      50 51       45 11
52 50      50 52       45 12
53 50      50 53       45 13
54 50      50 54       45 12
55 50      50 55       45 12

In [11]:
str(p1)

tibble [49 × 5] (S3: tbl_df/tbl/data.frame)
 $ Parcela : num [1:49] 3 3 3 3 3 6 6 6 6 6 ...
 $ NI      : num [1:49] 50 50 50 50 50 50 50 50 50 50 ...
 $ Plantula: num [1:49] 1 2 3 4 5 6 7 8 9 10 ...
 $ Ni      : num [1:49] 52 52 52 52 52 56 56 56 56 56 ...
 $ Altura  : num [1:49] 12 11 12 10 13 10 9 7 9 8 ...

### Ranges

In [ ]:
p1 <- read_excel("sample (1).xlsx", sheet=13, col_names=TRUE, range=cell_cols("A:c"))
head(p1)

  Parcela NI Plantula
1 3       50 1
2 3       50 2
3 3       50 3
4 3       50 4
5 3       50 5
6 6       50 6

In [10]:
p1 <- read_excel("sample (1).xlsx", sheet=13, col_names=TRUE, range=cell_rows(1:50))
tail(p1, n=3)

  Parcela NI Plantula Ni Altura
1 33      50 47       60  9
2 33      50 48       60  9
3 33      50 49       60 10

### Rename

col_names	
TRUE to use the first row as column names, FALSE to get default names, or a character vector giving a name for each column. If user provides col_types as a vector, col_names can have one entry per column, i.e. have the same length as col_types, or one entry per unskipped column

In [15]:
p1 <- read_excel("sample (1).xlsx",sheet="Plantulas",
                         col_names=c("IdParcela","N_I","IdPlantula","N_i","Altura"))
head(p1,n = 3)

  IdParcela N_I  IdPlantula N_i  Altura
1 Parcela   NI   Plantula   Ni   Altura
2 3.0       50.0 1.0        52.0 12.0
3 3.0       50.0 2.0        52.0 11.0

In [14]:
p1 <- read_excel("sample (1).xlsx",sheet="Plantulas",skip=1,
                         col_names=c("IdParcela","N_I","IdPlantula","N_i","Altura"))
p1

   IdParcela N_I IdPlantula N_i Altura
1   3        50   1         52  12
2   3        50   2         52  11
3   3        50   3         52  12
4   3        50   4         52  10
5   3        50   5         52  13
6   6        50   6         56  10
7   6        50   7         56   9
8   6        50   8         56   7
9   6        50   9         56   9
10  6        50  10         56   8
11  6        50  11         56  10
12  8        50  12         60   6
13  8        50  13         60   5
14  8        50  14         60   7
15  8        50  15         60   5
16  8        50  16         60   6
17  8        50  17         60   4
18 15        50  18         46   7
19 15        50  19         46   8
20 15        50  20         46   7
21 15        50  21         46   7
22 15        50  22         46   6
23 22        50  23         49  10
24 22        50  24         49  11
25 22        50  25         49  13
26 22        50  26         49  12
27 22        50  27         49  12
28 24        50  28         51  14
29 24        50  29         51  15
30 24        50  30         51  13
31 24        50  31         51  12
32 24        50  32         51  13
33 30        50  33         50   6
34 30        50  34         50   7
35 30        50  35         50   6
36 30        50  36         50   8
37 30        50  37         50   7
38 32        50  38         61   9
39 32        50  39         61  10
40 32        50  40         61   8
41 32        50  41         61   9
42 32        50  42         61   9
43 32        50  43         61  10
44 33        50  44         60   7
45 33        50  45         60  10
46 33        50  46         60   8
47 33        50  47         60   9
48 33        50  48         60   9
49 33        50  49         60  10
50 50        50  50         45  12
51 50        50  51         45  11
52 50        50  52         45  12
53 50        50  53         45  13
54 50        50  54         45  12
55 50        50  55         45  12

### Data Types

col_types	
Either NULL to guess all from the spreadsheet or a character vector containing one entry per column from these options: "skip", "guess", "logical", "numeric", "date", "text" or "list". If exactly one col_type is specified, it will be recycled. The content of a cell in a skipped column is never read and that column will not appear in the data frame output. A list cell loads a column as a list of length 1 vectors, which are typed using the type guessing logic from col_types = NULL, but on a cell-by-cell basis.

In [20]:
p1 <- read_excel("sample (1).xlsx",sheet="Plantulas",skip=1,
                          col_names=c("IdParcela","IdPlantula","N_i","Altura"),
                          col_types=c("text","skip","text","guess","numeric"))

p1

   IdParcela IdPlantula N_i Altura
1  3.0       1.0        52  12
2  3.0       2.0        52  11
3  3.0       3.0        52  12
4  3.0       4.0        52  10
5  3.0       5.0        52  13
6  6.0       6.0        56  10
7  6.0       7.0        56   9
8  6.0       8.0        56   7
9  6.0       9.0        56   9
10 6.0       10.0       56   8
11 6.0       11.0       56  10
12 8.0       12.0       60   6
13 8.0       13.0       60   5
14 8.0       14.0       60   7
15 8.0       15.0       60   5
16 8.0       16.0       60   6
17 8.0       17.0       60   4
18 15.0      18.0       46   7
19 15.0      19.0       46   8
20 15.0      20.0       46   7
21 15.0      21.0       46   7
22 15.0      22.0       46   6
23 22.0      23.0       49  10
24 22.0      24.0       49  11
25 22.0      25.0       49  13
26 22.0      26.0       49  12
27 22.0      27.0       49  12
28 24.0      28.0       51  14
29 24.0      29.0       51  15
30 24.0      30.0       51  13
31 24.0      31.0       51  12
32 24.0      32.0       51  13
33 30.0      33.0       50   6
34 30.0      34.0       50   7
35 30.0      35.0       50   6
36 30.0      36.0       50   8
37 30.0      37.0       50   7
38 32.0      38.0       61   9
39 32.0      39.0       61  10
40 32.0      40.0       61   8
41 32.0      41.0       61   9
42 32.0      42.0       61   9
43 32.0      43.0       61  10
44 33.0      44.0       60   7
45 33.0      45.0       60  10
46 33.0      46.0       60   8
47 33.0      47.0       60   9
48 33.0      48.0       60   9
49 33.0      49.0       60  10
50 50.0      50.0       45  12
51 50.0      51.0       45  11
52 50.0      52.0       45  12
53 50.0      53.0       45  13
54 50.0      54.0       45  12
55 50.0      55.0       45  12

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=cd2fca3f-dc64-4c71-8bd4-adda531fa911' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>