In [28]:
import pandas as pd
import numpy as np

In [10]:
mr = pd.read_html('https://en.wikipedia.org/wiki/List_of_cities_by_homicide_rate')
df_homicide = mr[0].copy(deep = True) #Copy a dataframe nicely
df_homicide

,Rank,City,Country,Homicides (2019),Population (2019),"Homicides per 100,000 per year"
0,1,Tijuana,Mexico,2367,1763197,134.24
1,2,Juárez,Mexico,1522,1455923,104.54
2,3,Uruapan,Mexico,301,351823,85.54
3,4,Irapuato,Mexico,723,895515,80.74
4,5,Obregón,Mexico,281,348154,80.72
5,6,Caracas,Venezuela,2134,2858933,74.65
6,7,Acapulco,Mexico,600,837914,71.61
7,8,Cape Town,South Africa,3065,4488545,68.28
8,9,St. Louis,United States,194,300576,64.54
9,10,Vitória da Conquista,Brazil,205,341597,60.01
10,11,Baltimore,United States,348,593490,58.64
11,12,Ciudad Guayana,Venezuela,462,799255,57.80
12,13,Kingston,Jamaica,680,1180771,57.59
13,14,Feira de Santana,Brazil,349,614872,56.76
14,15,San Pedro Sula,Honduras,436,789645,55.21
15,16,San Juan,United States,172,318441,54.01
16,17,Ensenada,Mexico,275,527584,52.12
17,18,Ciudad Bolívar,Venezuela,189,370627,51.01
18,19,Cuernavaca,Mexico,470,923274,50.91
19,20,Celaya,Mexico,262,526166,49.87
20,21,Culiacan,Mexico,472,955340,49.41
21,22,Natal,Brazil,645,1334817,48.32
22,23,"Salvador, Bahia",Brazil,1657,3490792,47.47
23,24,Nelson Mandela Bay (Port Elizabeth),South Africa,553,1207485,45.80
24,25,Cancún,Mexico,376,825647,45.54
25,26,Cali,Colombia,1176,2599468,45.24
26,27,Rio Branco,Brazil,183,407319,44.93
27,28,Caruaru,Brazil,160,361118,44.31
28,29,Guatemala City,Guatemala,1420,3265546,43.48
29,30,Zacatecas,Mexico,151,351397,42.95
30,31,Barquisimeto,Venezuela,489,1161709,42.11
31,32,Chihuahua,Mexico,391,937233,41.70
32,33,Distrito Central (Tegucigalpa),Honduras,516,1259646,40.96
33,34,Detroit,United States,273,670031,40.74
34,35,Durban,South Africa,1577,3890001,40.54
35,36,Manaus,Brazil,878,2182763,40.22
36,37,Palmira,Colombia,124,312507,39.68
37,38,Morelia,Mexico,325,819361,39.65
38,39,Ciudad Victoria,Mexico,139,363577,38.27
39,40,Guadalajara,Mexico,1932,5073583,38.07
40,41,Reynosa,Mexico,248,679229,36.57
41,42,Johannesburg,South Africa,2078,5738536,36.21
42,43,Minatitlán,Mexico,132,369213,35.75
43,44,Cúcuta,Colombia,303,852014,35.56
44,45,Recife,Brazil,1422,3999817,35.55
45,46,Valencia,Venezuela,486,1371267,35.41
46,47,León,Mexico,697,1987335,35.07
47,48,Maturin,Venezuela,184,526243,34.98
48,49,Fortaleza,Brazil,1365,3959923,34.47
49,50,Maceió,Brazil,347,1018948,34.05

In [11]:
df_homicide.head(2)

,Rank,City,Country,Homicides (2019),Population (2019),"Homicides per 100,000 per year"
0,1,Tijuana,Mexico,2367,1763197,134.24
1,2,Juárez,Mexico,1522,1455923,104.54

# Drop
Columns

In [12]:
#Don't delete the real data frame column, only in the output
df_homicide.drop('Population (2019)', axis = 1).head(5)

   Rank      City Country  Homicides (2019)  Homicides per 100,000 per year
0     1   Tijuana  Mexico              2367                          134.24
1     2    Juárez  Mexico              1522                          104.54
2     3   Uruapan  Mexico               301                           85.54
3     4  Irapuato  Mexico               723                           80.74
4     5   Obregón  Mexico               281                           80.72

In [14]:
df_homicide.head(3)

,Rank,City,Country,Homicides (2019),Population (2019),"Homicides per 100,000 per year"
0,1,Tijuana,Mexico,2367,1763197,134.24
1,2,Juárez,Mexico,1522,1455923,104.54
2,3,Uruapan,Mexico,301,351823,85.54

In [ ]:
# True delete
df_homicide.drop('Population (2019)', axis = 1, inplace = True)

In [19]:
df_homicide.head(5)

   Rank      City Country  Homicides (2019)  Homicides per 100,000 per year
0     1   Tijuana  Mexico              2367                          134.24
1     2    Juárez  Mexico              1522                          104.54
2     3   Uruapan  Mexico               301                           85.54
3     4  Irapuato  Mexico               723                           80.74
4     5   Obregón  Mexico               281                           80.72

In [20]:
#Default python keyword to delete a object
del df_homicide['City']

In [22]:
df_homicide[0:5]

   Rank Country  Homicides (2019)  Homicides per 100,000 per year
0     1  Mexico              2367                          134.24
1     2  Mexico              1522                          104.54
2     3  Mexico               301                           85.54
3     4  Mexico               723                           80.74
4     5  Mexico               281                           80.72

# Drop
Rows

In [23]:
df_homicide.drop([0,1,2], axis = 0).head(10)

    Rank        Country  Homicides (2019)  Homicides per 100,000 per year
3      4         Mexico               723                           80.74
4      5         Mexico               281                           80.72
5      6      Venezuela              2134                           74.65
6      7         Mexico               600                           71.61
7      8   South Africa              3065                           68.28
8      9  United States               194                           64.54
9     10         Brazil               205                           60.01
10    11  United States               348                           58.64
11    12      Venezuela               462                           57.80
12    13        Jamaica               680                           57.59

In [25]:
df_homicide.head(10)

   Rank        Country  Homicides (2019)  Homicides per 100,000 per year
0     1         Mexico              2367                          134.24
1     2         Mexico              1522                          104.54
2     3         Mexico               301                           85.54
3     4         Mexico               723                           80.74
4     5         Mexico               281                           80.72
5     6      Venezuela              2134                           74.65
6     7         Mexico               600                           71.61
7     8   South Africa              3065                           68.28
8     9  United States               194                           64.54
9    10         Brazil               205                           60.01

In [26]:
df_homicide.drop(range(0,10), axis = 0).head(10)

    Rank        Country  Homicides (2019)  Homicides per 100,000 per year
10    11  United States               348                           58.64
11    12      Venezuela               462                           57.80
12    13        Jamaica               680                           57.59
13    14         Brazil               349                           56.76
14    15       Honduras               436                           55.21
15    16  United States               172                           54.01
16    17         Mexico               275                           52.12
17    18      Venezuela               189                           51.01
18    19         Mexico               470                           50.91
19    20         Mexico               262                           49.87

# Add
Columns

In [27]:
df_homicide.head(5)

   Rank Country  Homicides (2019)  Homicides per 100,000 per year
0     1  Mexico              2367                          134.24
1     2  Mexico              1522                          104.54
2     3  Mexico               301                           85.54
3     4  Mexico               723                           80.74
4     5  Mexico               281                           80.72

In [30]:
df_homicide['New_Column'] = np.nan 
df_homicide.head(5)

   Rank Country  Homicides (2019)  Homicides per 100,000 per year  New_Column
0     1  Mexico              2367                          134.24         NaN
1     2  Mexico              1522                          104.54         NaN
2     3  Mexico               301                           85.54         NaN
3     4  Mexico               723                           80.74         NaN
4     5  Mexico               281                           80.72         NaN

In [35]:
data = np.arange(0, df_homicide.shape[0]) # 50 register in the dataframe
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [33]:
df_homicide['Range'] = data
df_homicide.head(10)

,Rank,Country,Homicides (2019),"Homicides per 100,000 per year",New_Column,Range
0,1,Mexico,2367,134.24,NaN,0
1,2,Mexico,1522,104.54,NaN,1
2,3,Mexico,301,85.54,NaN,2
3,4,Mexico,723,80.74,NaN,3
4,5,Mexico,281,80.72,NaN,4
5,6,Venezuela,2134,74.65,NaN,5
6,7,Mexico,600,71.61,NaN,6
7,8,South Africa,3065,68.28,NaN,7
8,9,United States,194,64.54,NaN,8
9,10,Brazil,205,60.01,NaN,9

# Add
Rows

In [37]:
df_homicide.head(10)

,Rank,Country,Homicides (2019),"Homicides per 100,000 per year",New_Column,Range
0,1,Mexico,2367,134.24,NaN,0
1,2,Mexico,1522,104.54,NaN,1
2,3,Mexico,301,85.54,NaN,2
3,4,Mexico,723,80.74,NaN,3
4,5,Mexico,281,80.72,NaN,4
5,6,Venezuela,2134,74.65,NaN,5
6,7,Mexico,600,71.61,NaN,6
7,8,South Africa,3065,68.28,NaN,7
8,9,United States,194,64.54,NaN,8
9,10,Brazil,205,60.01,NaN,9

In [38]:
df_homicide.append(df_homicide) # Now, there are 100 rows

/tmp/ipykernel_38979/1743406727.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_homicide.append(df_homicide)

,Rank,Country,Homicides (2019),"Homicides per 100,000 per year",New_Column,Range
0,1,Mexico,2367,134.24,NaN,0
1,2,Mexico,1522,104.54,NaN,1
2,3,Mexico,301,85.54,NaN,2
3,4,Mexico,723,80.74,NaN,3
4,5,Mexico,281,80.72,NaN,4
...,...,...,...,...,...,...
45,46,Venezuela,486,35.41,NaN,45
46,47,Mexico,697,35.07,NaN,46
47,48,Venezuela,184,34.98,NaN,47
48,49,Brazil,1365,34.47,NaN,48
49,50,Brazil,347,34.05,NaN,49